# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20160713_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiles',
            options={'ordering': ('user__first_name', 'user__last_name', 'user__email'), 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
