# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20160713_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiles',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AddField(
            model_name='profiles',
            name='first_name',
            field=models.CharField(max_length=254, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='last_name',
            field=models.CharField(max_length=254, null=True, verbose_name='Last name'),
        ),
    ]
