# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_remove_companies_profiles'),
        ('profiles', '0005_auto_20160713_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Companies', verbose_name='Company'),
        ),
    ]
