# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20160713_2121'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='profiles',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Profiles', verbose_name='Project'),
        ),
    ]
