# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160713_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='profiles',
            field=models.ManyToManyField(to='profiles.Profiles', verbose_name='Profiles'),
        ),
    ]
