# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 09:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Name')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('phone_number', models.CharField(blank=True, max_length=254, null=True, verbose_name='Phone number')),
                ('fax_number', models.CharField(blank=True, max_length=254, null=True, verbose_name='Fax number')),
                ('website_url', models.URLField(blank=True, max_length=254, null=True, verbose_name='Website')),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'verbose_name': 'company',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254, null=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=254, null=True, verbose_name='Last name')),
                ('job_title', models.CharField(blank=True, max_length=254, null=True, verbose_name='Job title')),
                ('phone_number', models.CharField(blank=True, max_length=254, null=True, verbose_name='Phone number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='time_tracker.Company', verbose_name='Company')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'profiles',
                'verbose_name': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Description')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Is finished')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('profiles', models.ManyToManyField(blank=True, to='time_tracker.Profile', verbose_name='Profiles')),
            ],
            options={
                'verbose_name_plural': 'projects',
                'verbose_name': 'project',
            },
        ),
    ]
