# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='time_tracker.Company', verbose_name='Company'),
        ),
    ]
