# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0004_timereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timereport',
            name='user',
        ),
        migrations.AddField(
            model_name='timereport',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='time_tracker.Profile', verbose_name='Profile'),
        ),
    ]
