# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0005_auto_20160720_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='timereport',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='timereport',
            name='seconds',
            field=models.TimeField(null=True, verbose_name='Seconds'),
        ),
    ]
