# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0007_auto_20160720_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timereport',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Name'),
        ),
    ]
