# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-10 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0009_auto_20160722_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timereport',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
