# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20160713_2046'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='profiles',
            field=models.ManyToManyField(to='profiles.Profiles', verbose_name='Profiles'),
        ),
    ]
