# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companies_profiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'ordering': ('name',), 'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterField(
            model_name='companies',
            name='profiles',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Profiles', verbose_name='Profiles'),
        ),
    ]
