# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('companies', '0005_auto_20160713_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='projects',
        ),
        migrations.AddField(
            model_name='companies',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='projects.Projects', verbose_name='Projects'),
        ),
    ]
