# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20160713_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='projects',
        ),
    ]
