# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20160713_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='profiles.Profiles', verbose_name='Profiles'),
        ),
    ]
